### ISSUE TITLE
exprs documentation

### ISSUE THREAD

**Issue by rspreafico** [davismcc/archive-scater#101]
In any function with an exprs_values argument, both tpm and exprs are indicated as being used by default (scater 1.3.42):

exprs_values	
character string indicating which values should be used as the expression values for this plot. Valid arguments are "tpm" (default; transcripts per million), "norm_tpm" (normalised TPM values), "fpkm" (FPKM values), "norm_fpkm" (normalised FPKM values), "counts" (counts for each feature), "norm_counts", "cpm" (counts-per-million), "norm_cpm" (normalised counts-per-million), "exprs" (whatever is in the 'exprs' slot of the SCESet object; default), "norm_exprs" (normalised expression values) or "stand_exprs" (standardised expression values) or any other slots that have been added to the "assayData" slot by the user.

**Comment by davismcc** [comment]
Thanks for the report! I have cleaned these up (usual default is "exprs", though this can vary depending on the function, e.g. `plotHighestExprs`). Fixed docs will appear in the next push.

Best wishes
Davis
