### ISSUE TITLE
plotQC documentation

### ISSUE THREAD

**Issue by rspreafico** [davismcc/archive-scater#103]
The following line in plotQC's help page shoud refer to findImportantPCs rather than plotImportantPCs:

...	
arguments passed to plotHighestExprs, plotImportantPCs, plotExplanatoryVariables and plotExprsMeanVsFreq as appropriate.

**Comment by davismcc** [comment]
Thanks for the bug report! I have fixed the documentation making that change and you'll see it pushed in the next commit. 

Best wishes
Davis
