### ISSUE TITLE
minor comment for the documentation of normalize()

### ISSUE THREAD

**Issue by friedue** [davismcc/archive-scater#107]
The function normalize.SCESet() has the default parameter `recompute_cpm = TRUE` - the current help text does not mention that the additional prerequisites for this parameter are (i) the presence of actual values within `cpm(sceSet)` and (ii) `exprs_values` must be set to “counts”. 

Since the default of the function that creates an sceSet object is to store cpm values in the `exprs()` slot, I was puzzled why `normalize()` would not re-compute the cpm values because I wasn't aware that they needed to be actually stored in the dedicated cpm() slot.

**Comment by davismcc** [comment]
This issue was moved to davismcc/scater#20
