### ISSUE TITLE
comment on the default perplexity setting for plotTSNE

### ISSUE THREAD

**Issue by friedue** [davismcc/archive-scater#108]
The default setting of the `plotTSNE` function for perplexity is n.cells/5 - that would be very high for Drop-seq data sets of better quality with more than 1000 cells -- the original tSNE paper recommends perplexity values between 5 and 50. In my hands, perplexity values of 20-40 indeed work better for larger cell numbers. I'm fine with the default, but perhaps it should be mentioned in the documentation that depending on the number of cells this should perhaps be adjusted.

**Comment by davismcc** [comment]
This issue was moved to davismcc/scater#19
