### ISSUE TITLE
Reading mtx (matrix market) files?

### ISSUE THREAD

**Issue by vals** [davismcc/archive-scater#109]
Hi,

I think it would be helpful with a file reader which reads the output from e.g. 10X Genomics Cell Ranger. This is a .mtx matrix market file (sparse matrix encoding), and two TSV files: One with gene information, and one with sample barcodes.

Given the popularity of 10X, it'll probably be useful, and a lot of people are confused about how to get the .mtx files in to R.

**Comment by LTLA** [comment]
We already have such a function in `read10XResults`; see `R/10ximport-wrapper.R`.

**Comment by vals** [comment]
Oh! Bah, the person I spoke said she checked! Never mind then.
