### ISSUE TITLE
different clustering results with rtsne() and plotTSNE() function

### ISSUE THREAD

**Issue by cmgraef** [davismcc/archive-scater#111]
Hi, 

thank you so much for providing such an amazing tool! Before using scater I made my tsne plots with the rtsne package. For a given single cell data set I get the following plot: 

https://ibb.co/mEna5k

Here's the code for that: 

```
library(Rtsne)

sc_expression <- t(read.csv("~scrna expression.csv", row.names=1))

tsne_plot <- Rtsne(sc_expression_matrix, check_duplicates = FALSE, perplexity = 50)
plot(tsne_plot$Y)

```
I obviously verified that result several times. When I ran the same data with the scater package I got this result: 

https://ibb.co/hvDhkk

Here is the code for that: 

```
library(Rtsne)
library(scater)

sc_example_counts <- read.csv("~scrna expression.csv", header=TRUE, row.names=1)
sc_example_cell_info <- read.csv("~phenotype.csv", row.names=1)

pd <- new("AnnotatedDataFrame", data = sc_example_cell_info)
example_sceset <- newSCESet(countData = sc_example_counts, phenoData = pd)

plotTSNE(example_sceset, perplexity = 50, colour_by = "cell_type")

```

I don't really understand how the results can be so different between the two packages especially since the plotTSNE() function uses the RTSNE package. Perplexity and other parameters are all the same. I would highly appreciate your advice on this! 

Thanks, 
Moritz

**Comment by LTLA** [comment]
_scater_ automatically uses the top 500 most variable genes as input into `Rtsne` - see the man page for details. Gene selection matters, so you'll obviously get different results than if you manually ran `Rtsne` on the entire count matrix.

**Comment by davismcc** [comment]
This issue was moved to davismcc/scater#17
