### ISSUE TITLE
plotHighestExprs

### ISSUE THREAD

**Issue by weizhiting** [davismcc/archive-scater#113]
![rplot](https://cloud.githubusercontent.com/assets/24773527/26317057/2d8384d8-3f51-11e7-802a-eb2c596317b6.png)
Hi,when i use this command,plotHighestExprs(example_sceset,exprs_values = 'exprs'),
i get the attached png,but seems the circle in the png is not at the right position?Thanks!

**Comment by davismcc** [comment]
This issue was moved to davismcc/scater#16
