### ISSUE TITLE
Number of dimensions error in calculateQCMetrics

### ISSUE THREAD

**Issue by samvidav** [davismcc/archive-scater#121]
Hi, 

I am trying to run quality control on a large dataset (9000 samples, 29000 genes), so I'm working with an SCESet that is about 13Mb in size. Whenever I run the calculateQCMetrics function, I get this error - 
`Error in pct_exprs_by_cell_sorted[1:500, ] : 
  incorrect number of dimensions`
The function works fine for the same data when I break it into smaller chunks, but is giving me this error when I try to run it on the entire set. Do you have any ideas as to what could be going wrong?

Thanks

**Comment by LTLA** [comment]
Are you sure you're using the latest version of _scater_? I don't think `pct_exprs_by_cell_sorted` exists any more.

**Comment by samvidav** [comment]
I think that might be it, I updated all my packages and it runs fine now.
