### ISSUE TITLE
Problem with runPCA function

### ISSUE THREAD

**Issue by lvkunz** [davismcc/archive-scater#135]
Hello,

Thanks a lot for the amazing work from your lab. I'm running the standR workflow and I encounter a problem when using the scater::runPCA function or drawPCA function. 

My guess is that the useNames = NA parameter (somewhere, not sure where) should be changed to useNames = FALSE.

Thanks a lot!
Louis

Here is the full error messages from R :

Error : useNames = NA is defunct. Instead, specify either useNames = TRUE or useNames = FALSE.

18. stop(errorCondition(msg, old = fname, new = new, package = package,
class = "defunctError"))
17.Defunct(msg = "useNames = NA is defunct. Instead, specify either useNames = TRUE or useNames = FALSE.",
package = .packageName)
16.deprecatedUseNamesNA()
15.matrixStats::rowVars(x, rows = rows, cols = cols, na.rm = na.rm,
center = center, dim. = dim., ..., useNames = useNames)
14..local(x, rows, cols, na.rm, center, ..., useNames = useNames)
13.candidate(S, ..., useNames = useNames)
12.smart_seed_dispatcher(x, generic = MatrixGenerics::rowVars,
blockfun = .DelayedMatrix_block_rowVars, force_block_processing = force_block_processing,
rows = rows, cols = cols, na.rm = na.rm, center = center,
..., useNames = useNames)
11..local(x, rows, cols, na.rm, center, ..., useNames = useNames)
10.rowVars(DelayedArray(x))
9.rowVars(DelayedArray(x))
8..get_mat_for_reddim(x, subset_row = subset_row, ntop = ntop,
scale = scale, get.var = TRUE)
7..local(x, ...)
6.scater::calculatePCA(object, ncomponents = maxdim)
5.scater::calculatePCA(object, ncomponents = maxdim)
4.calcPCA(assay(object, assay), dims)
3..local(object, dims, ...)
2.drawPCA(spe, assay = 2, color = Segment)
1.drawPCA(spe, assay = 2, color = Segment)

**Comment by alanocallaghan** [comment]
You should close this, this isn't the current scater repo

**Comment by lvkunz** [comment]
yes realised afterwards sorry about this
