### ISSUE TITLE
Add a `get_exprs` (or similar) function for use by other packages

### ISSUE THREAD

**Issue by davismcc** [davismcc/archive-scater#18]
I think a use_for_exprs slot is a great idea, I also think it's worthwhile implementing a function like

``` r
get_exprs <- function(object) {
x <- NULL
if(object@use_for_expression == "TPM") {
x <- tpm(object)
} else if .... etc 
return( x )
}
```

**Comment by davismcc** [comment]
[Just moving discussion from other thread...]

First thoughts on implementing a get_exprs function:
- I think that name's actually pretty good, but if you have any inspiration, go for it.
- You might find the `switch` function/syntax useful to avoid a large number of if/else statements.
- Providing a warning if slot designated by `use_for_expression` is actually empty (i.e. `NULL`).

**Comment by kieranrcampbell** [comment]
useForExprs slot & getExprs method added in previous two commits respectively.
