### ISSUE TITLE
Throw error if argument key not found

### ISSUE THREAD

**Issue by kieranrcampbell** [davismcc/archive-scater#21]
`plotTSNE(object, argdoesnotexist = 1)`
doesn't throw any error, which would be useful if someone spells an argument wrong (I got this after `perlexity`). Not sure how common this is across other functions that pass arguments by ellipses or if it's an easy fix

**Comment by davismcc** [comment]
Hmmm, good catch. I had always trusted R to pick up when function arguments are misspecified like that. It could be that with the object orientation things like that can get lost. I'll take a look.

**Comment by davismcc** [comment]
No traffic on this for almost a year, so closing as not a serious issue/priority.
