### ISSUE TITLE
Add assayData accessor generator function

### ISSUE THREAD

**Issue by davismcc** [davismcc/archive-scater#23]
To make convenient, customisable use of the assayData slot of an SCESet object.

Slots in assayData can be defined manually:

``` r
example_sceset@assayData$transformed_counts <- transformed_counts_matrix
example_sceset@assayData$transformed_counts
```

But this is not very elegant and perhaps not intuitive. So perhaps we could have a function like:

``` r
## either
make_accessor("transformed_counts")
## or
transformed_counts <- make_accessor("transformed_counts")
```

So that now there is a method `transformed_counts` that can be used to access and assign data from/to `example_sceset@assayData$transformed_counts` in the SCESet object.

Fiddly things could arise if we want to make it a proper SCESet method. Accessor capability should be easy, assignment perhaps a bit trickier.

**Comment by kieranrcampbell** [comment]
This is a nice idea. One aspect that might be quite tricky is subsetting unless we're assuming all assayData objects are of the same dimension as the SCESet (you might need a slot for some orthogonal data source). One option is to implement subsetting if the dimensions are consistent (e.g. if the SCESet is dimension n by p and the new assayData is n by q then just subset the n, etc).

**Comment by davismcc** [comment]
Yes, for assayData it's easy - assignment will fail if the matrix being added is not of the correct dimension. So I think for this particular application (more elements/slots within assayData) things are straight-forward.

We do need orthogonal slots, though, you're absolutely right. That's trickier, esp with subsetting. I'll open another issue for that.

**Comment by qfwills** [comment]
Will comment more on [issue #24](https://github.com/davismcc/scater/issues/24), but definitely a good idea me thinks for allowing flexible data normalisation and adding other functional data related to the same cells (imaging, ATAC etc.)

**Comment by davismcc** [comment]
I've added the function `get_exprs` to access assayData data. It takes as arguments an SCESet object and a character string naming the slot to access.
e.g.

``` r
get_exprs(sceset_object, "exprs") # returns exprs data 
get_exprs(sceset_object, "blergh") # returns NULL unless you have manually added a slot "blergh"
```

**Comment by davismcc** [comment]
I have now also added a function `set_exprs` function to conveniently assign new data to the assayData slot of an object. Syntax designed to mirror that of `get_exprs`:

``` r
set_exprs(sceset_object, "new_exprs") <- new_expression_matrix
set_exprs(sceset_object, "scaled_counts") <- t(t(counts(example_sceset)) / colSums(counts(example_sceset)))
```
