### ISSUE TITLE
Add methods for orthogonal data slots

### ISSUE THREAD

**Issue by davismcc** [davismcc/archive-scater#24]
We may want to have more general/flexible slots in an SCESet object. 

For example, can we add ATAC data to an SCESet object that can have different dimensions from the expression data? 

Hard coding such a slot(s) should be possible. Making it possible for the user to create their own slots requires some more thought, as it would perhaps need "redefining" the SCESet object - we need to explore this.

Subsetting is going to be tricky. We may insist that the number of cells/samples has to be the same. So we can only have expression matrices of shape $ngenes by ncells$ and ATAC (or other) matrices of the form $nregions \* ncells$. In that way, subsetting by cells will be fine. We may need specific methods to subset the non-expression data. So normal "row" subsetting of an SCESet object will subset expression features (genes, transcripts) as now (backward compatible, default use, which I like), but to subset non-expression data there's a specific method: `subset_atac()` for instance (off the top of my head).

One general concern is how large non-expression data could get. e.g. imputed genotypes for 7 million variants is not going to play nicely in R. I imagine a few hundred thousand features for a few thousand cells will be OK, but expect problems with performance beyond that.

**Comment by qfwills** [comment]
It seems likely to me that over the next year we will start seeing more complementary functional data generated around scRNA-seq e.g. ATAC, imaging, targeted scDNA-seq. These will have their own feature metadata for the cells. Perhaps subsetting should come in _n_ flavours driven by the _n_ number of feature metadata files?

Assuming targeted scDNA-seq is the sweet spot for integration with scRNA-seq and scATAC-seq, my hunch is that size won't be an issue for a while. Say he confidently...

**Comment by davismcc** [comment]
The new `MultiAssayExperiment` package on Bioconductor (https://github.com/vjcitn/MultiAssayExperiment) should help with this. Aim to do this for the late 2016 release cycle.

**Comment by davismcc** [comment]
Closing this as a duplicate of the `MultiEssayExperiment` issue.
