### ISSUE TITLE
plotPCA/tSNE "size_by"/"color_by" to include gene names

### ISSUE THREAD

**Issue by kieranrcampbell** [davismcc/archive-scater#25]
It's really useful to be able to size or colour reduced dimension representations by the expression of a particular gene, e.g. if you're wanting to see if that pseudotime trajectory is actually correlated with a marker gene. 

I'd suggest size/colour_by searches `names(pData(sce))` first, then through `featureNames(sce)`. Happy to implement if people think this is a good idea

**Comment by davismcc** [comment]
This is already done. 

Can you try it out and see where it breaks? It worked for me a little while ago, but I haven't tested it again on different data recently and it  could definitely do with some stress testing.

**Comment by kieranrcampbell** [comment]
This works very nicely!

**Comment by davismcc** [comment]
Just committed a further bug fix. Should be all good, but pipe up if not!
