### ISSUE TITLE
New QC metrics

### ISSUE THREAD

**Issue by kieranrcampbell** [davismcc/archive-scater#30]
Hi both,

I'd like to add two metrics calculated in calculateQCMetrics:
- n_detected_endogenous_features
- pct_tpm_top_100_endogenous_features (and possibly top_500 too) 
  as these are used in the wtchg qc pipeline. 
  If these are okay with everyone, I'll go ahead and add them

**Comment by qfwills** [comment]
There is a WTCHG QC pipeline using this?

I use % read counts in top 50.
Read counts   = more useful to see where the reads are going.
I.e. the % reads consumed by the top 50.
Thought TPMs don't hurt.

I'd say adding % mitocondrial genes is also a safe bet.
But still requires careful interpretation in the context of other metrics.

That should cover most things, except sequencing bias.
But that needs to come from PICARD etc.
Which is actually unsatisfactory and not optimal for single-cell.
Have BSG working on a custom sequencing bias metric.

Q

**Comment by kieranrcampbell** [comment]
There is a wtchg qc pipeline, but it doesn't use scater (hence mimicking
functionality would be a pretty good bet). Eshita says plotting those two
metrics against each other gives you a good idea of 'good' and 'bad' cells
(and having done this for the opdc test plate I'm inclined to agree).

**Comment by davismcc** [comment]
OK, I'm calling @kieranrcampbell out for saying that he would add these QC metrics and not. Disappointing follow-through, boss.

To update: 
- the `total_features` metric actually reports the number of endogenous genes expressed (deep in the function feature controls are subsetted out when computing this)
- I have added `pct_[tpm|counts]_top_X_endogenous_features` for X = [50, 100, 200, 500]

Don't make me do your job, Kieran.

**Comment by kieranrcampbell** [comment]
Sorry dude, my bad, definitely slipped up on this (and pct_dropouts earlier this week). Will get on the fixes faster in future.

**Comment by davismcc** [comment]
Haha, don't worry! These are just my hilarious jokes after a day of debugging and closing issue ;P
