### ISSUE TITLE
I got the error messages only for some plots

### ISSUE THREAD

**Issue by icebing** [davismcc/archive-scater#34]
Hi Developer,

I got the error messages only for two plots not for other plots. Any idea?

Tia.

plot(sceset, block1 = "Plate", block2 = "Input", colour_by = "Approach", nfeatures = 500, exprs_values = "counts")
Error in eval(expr, envir, enclos) : 
  object 'Proportion_Library' not found

plotQC(sceset, type = "highest-expression")
Error in `$<-.data.frame`(`*tmp*`, "Var2", value = integer(0)) : 
  replacement has 0 rows, data has 28800

**Comment by davismcc** [comment]
Hi Tia

Could you please provide the full code that has led you to these errors? Please also provide the output from `sessionInfo()` so that I can see the versions of packages that you are using. I can't diagnose what might have gone wrong with just the output you have provided. 

Best wishes
Davis
