### ISSUE TITLE
Show the fitted dropout line in plotExprsFreqVsMean

### ISSUE THREAD

**Issue by LTLA** [davismcc/archive-scater#38]
A trend is fitted to the technical controls in `plotExprsFreqVsMean` to define the mean-dependent drop-out rate, above which the number of genes is counted and reported. Can this trend be shown on the plot, to facilitate the explanation of the reported value?

Also, reporting "genes above high technical dropout" is confusing. It seems to refer to genes with _more_ dropouts, whereas being above the trend should be equivalent to having fewer dropouts.

**Comment by davismcc** [comment]
I've changed the text so it now says "genes with high technical dropout", so I hope that's less confusing.

I'll add the fitted line, but after the imminent Bioconductor release.

**Comment by LTLA** [comment]
I must confess that I'm still confused; is the reported value the number of genes above the line? Or below it? I always thought that genes above the line would have a lower dropout rate than the technical controls, because they would be observed in a higher proportion of cells.

**Comment by davismcc** [comment]
Added a smoothed fit to the plot (just loess), and clarified the annotation to the plot that we give the number of genes with mean expression above the value that corresponds to a 50% dropout rate for feature controls. There in the latest commit.
