### ISSUE TITLE
Colour plots according to arbitrary cell metrics

### ISSUE THREAD

**Issue by LTLA** [davismcc/archive-scater#39]
Can the `colour_by` argument in `plotPCA` and friends accept vectors (factors or numeric values) with which coloration can be performed? Currently, it seems I have to do something like this:

``` r
sce$whee <- arbitrary.values
plotPCA(sce, colour_by="whee")
```

... rather than the simpler one-step:

``` r
plotPCA(sce, colour_by=arbitrary.values)
```

**Comment by davismcc** [comment]
I'll add this, but it will be after the Bioconductor release, I'm afraid.

**Comment by LTLA** [comment]
Yeah, that's fine.

**Comment by LTLA** [comment]
This is now supported in #92. If you supply a one-column `data.frame` as `colour_by`, the various plotting functions will use those values to colour (or shape or size) values.

**Comment by davismcc** [comment]
This issue was moved to davismcc/scater#24
