### ISSUE TITLE
Formally defined getters and setters for size factors

### ISSUE THREAD

**Issue by LTLA** [davismcc/archive-scater#41]
Can the `sizeFactors` getter and setter methods be defined for `SCESet` objects? It should be a simple matter of adding a `size_factors` column to the `pData`. The same can be done for normalization factors, though it seems that size factors might be simpler to work with, given that the former depends on the library size (and thus has to be updated upon subsetting, etc.) whereas the latter does not.

**Comment by davismcc** [comment]
To be clear, are you envisaging size factors such as those computed from `edgeR::calcNormFactors` or `DESeq2::estimateSizeFactors`, that is values around 1?

**Comment by davismcc** [comment]
This is now implemented.
