### ISSUE TITLE
Defining the normalize method for SCESets

### ISSUE THREAD

**Issue by LTLA** [davismcc/archive-scater#42]
Can the `normalize` method be defined for a `SCESet`? I'm thinking of something that just recalculates the `cpm` and `exprs` fields based on pre-computed size factors, rather than something that calculates the factors themselves (the latter task probably involves enough work and attention that it requires a separate function call). I'd expect something like this would be in the function body:

``` r
normalize.body <- function(sceset, logExprsOffset=1, recompute.cpm=TRUE) {
    if (recompute.cpm) { 
        cpm(sceset) <- cpm(countData) # account for subsetting since initialization?
    }
    SFs <- sizeFactors(sceset) # assuming defined, see issue #41
    exprs(sceset) <- cpm.default(countData, prior.count = logExprsOffset, 
        lib.sizes=SFs * 1e6, log = TRUE)
    return(sceset)
}
```

This effectively returns log-"normalized counts" in `exprs`, which should be interpretable on the same scale as the raw counts if the size factors are centred around unity.

**Comment by davismcc** [comment]
Done.
