### ISSUE TITLE
Dplyr-style verbs for scater

### ISSUE THREAD

**Issue by kieranrcampbell** [davismcc/archive-scater#43]
I'm a big fan of [dplyr](https://cran.rstudio.com/web/packages/dplyr/vignettes/introduction.html) for manipulating data frames and I think the same could be very easily applied to scater, in particular implementing 
- `filter`
- `rename`
- `mutate`

and possibly `group-by`. 

For example, if you want to subset an `SCESet` currently you need to call something like

```
sce <- sce[sce$pct_dropout < 70, ]
```

whereas under the dplyr formalism this would become

```
sce <- filter(sce, pct_dropout < 70)
```

Similarly if we want a new column in pData we could call

```
sce <- mutate(sce, low_dropout = pct_dropout < 70)
```

rather than the current

```
pData(sce)$low_dropout <- sce$pct_dropout < 70
```

Since ExpressionSets have fData too you could easily extend this to check if the arguments were referring to pData and if not subset on fData, e.g.

```
sce <- filter(sce, n_cells_exprs > 50)
```

etc. 

A nice consequence is you could then override [magrittr](https://cran.r-project.org/web/packages/magrittr/vignettes/magrittr.html)'s `%>%` operator to chain things together, so you could do

```
sce <- sce %>%
   filter(n_cells_exprs > 50) %>%
   mutate(low_dropout = pct_dropout < 70) %>%
   calcualteQCMetrics()
```

which I think would be really nice!

If people like this idea I would be happy to implement as it should fairly simply involve function calls to the underlying dataframes.

**Comment by davismcc** [comment]
I'm happy to support this.

Only worry is NAMESPACE clashes with filter etc from dplyr and so on, but given that we will define it as an SCESet method I think this should be OK. 

It would be great if you could implement and then I can check and incorporate into the package. If done quickly we could squeeze into release. 

You may need to define generics for the verbs (if they do not already feature in the `BiocGenerics` package) before adding SCESet methods for them.

Let me know how you get on :)

**Comment by kieranrcampbell** [comment]
I have this working for `pData` with the methods `filter`, `mutate`, `arrange` and `rename`. What's nice is using `library(magrittr)` means the `%>%` operator works out of the box on `SCESet`s. However, integrating it with `fData` is a little trickier. I think there are two options:
1. Common verbs for both, e.g. `filter(sce, pct_dropout < 20, n_cells_exprs > 80)`. This takes a bit of work as you have to tokenize the expressions then send off to either be parsed in `pData` or `fData`. This is fine in simple cases but if you had something like `n_cells_exprs > 80 & mean_exprs > 20` you would need to tokenize to pull out `n_cells_exprs` and `mean_exprs`.
2. Implement separate verbs for `fData`, i.e. `ffilter`, `fmutate`, `farrange` and `frename`. This has the advantages of being less ambiguous and will be super fast to implement (can easily get into next release).

Any preference?

**Comment by davismcc** [comment]
As discussed yesterday, let's just include these verbs for `pData` for this release and work on common verbs for `fData` for the next release.

**Comment by kieranrcampbell** [comment]
Added `mutate`, `filter`, `rename` and `arrange`.
- Generics at the end of AllGenerics.R, everything else in verbs.R.
- Methods don't sanity check the inputs as this requires complex parsing and `dplyr` errors are meaningful anyway.
- Added `magrittr` as a suggests so `%>%` can be used.
- Passes `devtools::check()` with two (unrelated) NOTES

**Comment by davismcc** [comment]
This looks great - love it. Thanks!

I'm going to close this issue now. Let's raise a new one after release for dealing with fData verbs.
