### ISSUE TITLE
PCA and tSNE plots are not working in a loop

### ISSUE THREAD

**Issue by kokonech** [davismcc/archive-scater#49]
The package is really effective and has high quality in my opinion! However, I have a small issue: plotting PCA or tSNE in a  loop does not work. 

Basically, I would like to see how the expression of some specific genes is distributed in PCA and tSNE among samples to be confirmed with possible clustering. Therefore I add additional columns to pData, each containing expression of a selected gene. Than I perform plots, something like this:

```
names <- c( "Atoh1",  "Ptf1a" )

scater::plotTSNE(res.qc[endog_genes,], ntop = 500, preplexity = 50,
                 colour_by = names[1],  size_by = "total_features", 
                 shape_by = "state", exprs_values = "cpm", rand_seed=42 )


scater::plotTSNE(res.qc[endog_genes,], ntop = 500, preplexity = 50,
                 colour_by = names[2],  size_by = "total_features", 
                 shape_by = "state", exprs_values = "cpm", rand_seed=42 )
```

This code works. However, when I put everything in a loop it fails: 

```
for (n in names) {
  print(n)
  scater::plotTSNE(res.qc[endog_genes,], ntop = 500, preplexity = 50,
                 colour_by = n,  size_by = "total_features", 
                 shape_by = "state", exprs_values = "cpm", rand_seed=42 )

}

```

There is no error report, but no plots are created. It's no problem when there are only 2 genes, but I have up to 50. Why could this happen? Is it possible to fix this?

**Comment by kieranrcampbell** [comment]
Have you tried wrapping your plot calls in print statements? So

``` r
  print( scater::plotTSNE(res.qc[endog_genes,], ntop = 500, preplexity = 50,
                 colour_by = n,  size_by = "total_features", 
                 shape_by = "state", exprs_values = "cpm", rand_seed=42 ) )
```

**Comment by kokonech** [comment]
Yep, with print() statement everything worked!  Looks like this is a typical approach for ggplot object. Thanks a lot for quick reply! This issue can be closed now.

**Comment by kieranrcampbell** [comment]
Awesome, enjoy scater.
