### ISSUE TITLE
Argument check in plotSCESet

### ISSUE THREAD

**Issue by brisk022** [davismcc/archive-scater#53]
This is a minor issue. In the `plotSCESet` function, there is an argument check `exprs_values <- match.arg(exprs_values, c("exprs", "tpm", "fpkm", "counts"))`. However, the provided example data set also contains cpm values. So, when you try to select cpm on the plot tab in shiny, it gives you an illegal argument error. The argument list should probably be extended to include cpm.

**Comment by davismcc** [comment]
Hi @brisk022 

thanks for the bug report - you're absolutely right that cpm should be supported. I've fixed this in commit #910df55.

Best
Davis
