### ISSUE TITLE
Add option to colour points on plots by expression of a feature

### ISSUE THREAD

**Issue by davismcc** [davismcc/archive-scater#6]
Especially for t-SNE and PCA plots - useful for identifying cell types from clusters and visualisations.

**Comment by kieranrcampbell** [comment]
Also size of points corresponding (log) gene expression?

**Comment by davismcc** [comment]
Yes, when I add this I'll add colour, size and shape (can discretise a continuous variable - not that I would expect this to be used often)

**Comment by davismcc** [comment]
So I think I'll do this just to use expression values in the `exprs` slot. While it would be possible to do otherwise, the package assumes that what's in the `exrps` slot is what the user wants to use, so I think that's reasonable. Let me know if you think it would be particularly useful to specify counts, tpm, fpkm, norm_exprs or something else, though.

**Comment by kieranrcampbell** [comment]
This is something we might want to think about in general - when building an external package (e.g. embeddr) you want generic access to whatever measurement of expression the user fancies (counts, tpm, etc) for your analysis, so it might be worth having a flag of object@use_for_exprs so the user can set what's returned by exprs when an external package accesses it?

**Comment by davismcc** [comment]
OK, couple of updates/thoughts:
1. I have implemented the option to colour and size points by feature expression (that is, values from `exprs(object)` for `plotPCA`, `plotTSNE` and `plotReducedDim`.
2. Adding this option for `plotPhenoData` requires more substantial redesign of that code (and the `plotMetadata` function) - I think this will be worthwhile, but if you disagree, then let me know before I spend substantial time on it.
3. The motivation for using `exprs` is that it is a mandatory slot for `ExpressionSet` objects, and thus for `SCESet` objects. Therefore, I know that an `SCESet` object will always have `exprs` data. That said, it's not adding much overhead to add a `use_for_exprs` string slot to the `SCESet` class and set this to `exprs` by default. The functions that have a `use_as_exprs` argument can then grab that string by default. Would that be substantially useful for `embeddr`? If so, happy to add it.

**Comment by kieranrcampbell** [comment]
Re 2. - I hope to spend some of tomorrow going through scater stuff so will look more closely then. Still trying to find a really nice dataset for a work through from fastq -> some bio insight.

Re 3. I think a use_for_exprs slot is a great idea, I also think it's worthwhile implementing a function like
get_exprs <- function(object) {
x <- NULL
if(object@use_for_expression == "TPM") {
 x <- tpm(object)
} else if .... etc 
return( x )
}
since presumably any function that requires object@use_for_exprs will implement exactly that. Happy to do tomorrow if you agree (though a good name would be helpful)

**Comment by davismcc** [comment]
Cool cool.

I was curious, so I implemented colour/fill by continuous variables (incl feature expression levels) for `plotPhenoData` (`plotMetadata`) - see if you can break it!

I think you've persuaded me of the value of a `get_exprs` function or similar. Great if you could have a crack at this (and anything else) today/tomorrow. I can have another look at scater stuff again tomorrow afternoon. 

First thoughts on implementing a `get_exprs` function:
- I think that name's actually pretty good, but if you have any inspiration, go for it.
- You might find the `switch` function/syntax useful to avoid a large number of if/else statements.
- Providing a warning if slot designated by `use_for_expression` is actually empty (i.e. `NULL`).

I'm going to close this issue now and open `get_exprs` as a new issue. Re-open this, though if you break the plotting functions :)
