### ISSUE TITLE
pct_dropout is actually 100 - pct_dropout

### ISSUE THREAD

**Issue by kieranrcampbell** [davismcc/archive-scater#63]
in `R/qc.R` the calculation of percent dropout actually calculates the percentage of genes expressed in each cell. Specifically

``` r
100 / nrow(object) * nexprs(object, subset.row = NULL)
```

should be

``` r
100 * (1 - nexprs(object, subset.row = NULL) / nrow(object) )
```

I am happy to fix unless there is any disagreement on the definition here.

**Comment by davismcc** [comment]
Whoops. Please fix!

**Comment by davismcc** [comment]
Fixed in latest commit.
