### ISSUE TITLE
is_exprs() not working

### ISSUE THREAD

**Issue by wikiselev** [davismcc/archive-scater#64]
Hi Davis,

Looks like is_exprs() returns NULL for any SCESet object. E.g. this code provides NULL:
data("sc_example_counts")
data("sc_example_cell_info")
example_sceset <- newSCESet(countData = sc_example_counts)
is_exprs(example_sceset)

Could you please check this?

**Comment by wikiselev** [comment]
I just tried to rebuild the course materials after updating all the packages and this bug popped up.

**Comment by davismcc** [comment]
Yes, to save space we decided to deprecate storing is_exprs by default in new SCESet objects. `is_exprs` is trivially easy to calculate as required, and `is_exprs()` still works for accessing and assigning the matrix. We compute it on the fly when needed for some of the QC metrics and so on. 

`is_exprs(example_sceset) <- counts(example_sceset) > 1` will still work. 

Let me know if you find this causing any further downstream problems, but for the next release this is a feature and not a bug ;)

**Comment by wikiselev** [comment]
Ok, cool, a feature, not a bug! :-)
Thanks for a quick reply!

**Comment by LTLA** [comment]
On a related note, see `nexprs`, an efficient way to compute the number of cells in which a gene is expressed. Should be a bit better than running `rowSums` on the `is_exprs` output.
