### ISSUE TITLE
Calculation of top percentage for endogenous genes

### ISSUE THREAD

**Issue by LTLA** [davismcc/archive-scater#65]
The lines of code at 461 to 463 of `qc.R` are unsafe, as they do not protect against the possibility that the number of rows in the subsetted matrix `exprs_mat[,-is_feature_control]` is less than the values in `top.number`. It is also memory-inefficient, as it generates a copy of `exprs_mat`, which is precisely what we were trying to avoid by moving it into C++.

**Comment by davismcc** [comment]
Thanks for catching this, Aaron. 

Sent from mobile

On Sun, Oct 9, 2016 at 1:41 AM +0100, "Aaron Lun" notifications@github.com wrote:

The lines of code at 461 to 463 are unsafe, as they do not protect against the possibility that the number of rows in the subsetted matrix exprs_mat[,-is_feature_control] is less than the values in top.number. It is also memory-inefficient, as it generates a copy of exprs_mat, which is precisely what we were trying to avoid by moving it into C++.

**Comment by davismcc** [comment]
Thanks, again, Aaron. I've merged your pull request, and it passes R CMD check on Mac OS X and linux, so that looks good.
