### ISSUE TITLE
Calculation of top percentages for feature controls

### ISSUE THREAD

**Issue by LTLA** [davismcc/archive-scater#67]
The use of the top percentages computed from `.get_qc_metrics_exprs_mat` as the percentages of feature controls in `.process_feature_controls` is not correct. The calculated values _always_ refer to the top percentages of the supplied `exprs_mat`, regardless of what `is_feature_controls` is. Does it even make sense to compute the top percentages for the controls? For the ERCCs, the percentages of the top 100-500 values would always be 100%, because there are only 92 transcripts anyway.

**Comment by davismcc** [comment]
I agree that it doesn't make sense to get top percentages for feature controls. Top percentages from all features (controls included) and endogenous features make sense and are useful, but on reflection I can't see any use for top percentages for the controls. 

I've removed this behaviour from `.process_feature_controls` in the latest commit. Thanks for spotting.
