### ISSUE TITLE
Update CITATION file

### ISSUE THREAD

**Issue by davismcc** [davismcc/archive-scater#78]
Manuscript accepted. Boom. 💥

**Comment by cwcyau** [comment]
congrats


Dr Christopher Yau

Associate Professor in Applied Statistical Genomics
Wellcome Trust Centre for Human Genetics
University of Oxford

Reader in Computational Biology [from Jan 2017]
Centre for Computational Biology
Institute of Cancer and Genomic Sciences
University of Birmingham

www: http://cwcyau.github.io

**Comment by davismcc** [comment]
Wow, impressive monitoring of the scater issues!!!

**Comment by LTLA** [comment]
Added in #92, though volume/page number not yet available; this will need to be updated upon publication.
