### ISSUE TITLE
readKallistoResults fails when log not supplied

### ISSUE THREAD

**Issue by kieranrcampbell** [davismcc/archive-scater#9]
If user has run kallisto externally and wants to read in results then kallisto_log is NULL but code still tries to iterate over. Happy to fix

**Comment by davismcc** [comment]
Nice one, Kieran - thanks for the fix. What was the change needed?

**Comment by kieranrcampbell** [comment]
If you run kallisto yourself then the log object isn't created as per
runKallisto function, but readKallisto was still trying to use it to work
out which runs failed. I've set it up so if the user supplies the
directories with the output of kallisto runs then scater assumes all runs
were successful. Also kallisto_version wasn't passed to the second
invocation of readKallistoResultsOneSample

**Comment by davismcc** [comment]
Ah, OK, yes oversights on my behalf. Thanks for the fixes :)
